file = open("file_2.txt", "r")
content = file.read()
print(f"Содержимое файла: \n {content}")
file = open("file_2.txt", "r")
content = file.readlines()
print(f"Количество строк в файле: {len(content)}")
file = open("file_2.txt", "r")
content = file.readlines()
for i in range(len(content)):
    print(f"Количество символов {i + 1} строки: {len(content[i])}")
file = open("file_2.txt", "r")
content = file.read()
content = content.split()
print(f"Всего слов: {len(content)}")
file.close()